POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

# {
#   "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY2MTMxNjA2OCwianRpIjoiNTFjYmM2NTgxZDEzNDg2YTgwMjc2ZmEzZjM4MWEzYzAiLCJ1c2VyX2lkIjoxfQ.uk_iOfJemeXsP1Q8rykNJkFI8NqSJ5hW5pYqE63v7BY",
#   "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYxMzE2MDY4LCJqdGkiOiIwMmUwZjVlMDRkNTE0MzQ3OTFlMjcyMjk3NjVhYmI3NSIsInVzZXJfaWQiOjF9.b2GXWvszbl_-g1yw837yEWUsxvBrs76r1D6dmX56Omk"
# }

###
GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5OTMwMTI3LCJqdGkiOiIyNjJhNDgyZDJjNWE0NjRjYmFlNTUzNWQ3ODdkNzU5NiIsInVzZXJfaWQiOjF9.cyS12C-L8UBsDK3ZSqmLAxBSlKWu19_DfBPHl8YdaWg
content: application/json


###
GET http://127.0.0.1:8000/store/customers/me/ HTTP/1.1
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5OTMwMTI3LCJqdGkiOiIyNjJhNDgyZDJjNWE0NjRjYmFlNTUzNWQ3ODdkNzU5NiIsInVzZXJfaWQiOjF9.cyS12C-L8UBsDK3ZSqmLAxBSlKWu19_DfBPHl8YdaWg

###
GET http://127.0.0.1:8000/store/customers/ HTTP/1.1
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5OTMwMTI3LCJqdGkiOiIyNjJhNDgyZDJjNWE0NjRjYmFlNTUzNWQ3ODdkNzU5NiIsInVzZXJfaWQiOjF9.cyS12C-L8UBsDK3ZSqmLAxBSlKWu19_DfBPHl8YdaWg


###
PUT http://127.0.0.1:8000/store/customers/me/ HTTP/1.1
content-type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5NzYyMTE1LCJqdGkiOiJmODY4NmM5Mzc1NzM0Y2Q2OTllMjRkNTc5M2NmNDU0OSIsInVzZXJfaWQiOjF9.VOeg6sdV-dZySkQ8rcs3tF9rkUgMEZbpbwa8GSZQUjE

{
  "phone": "123456789"
}
