GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5NTYwNTA5LCJqdGkiOiIzZTgwN2NlYjhmNmQ0ODc3YWI5MzRlZDcyYzRiZGQ2OSIsInVzZXJfaWQiOjF9.bw_QXaqUVzYGHowcqtT_awDLe2XSQKb93oxeoLk_FoQ
content: application/json


###
GET http://127.0.0.1:8000/store/customers/me/ HTTP/1.1
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5NTYwNTA5LCJqdGkiOiIzZTgwN2NlYjhmNmQ0ODc3YWI5MzRlZDcyYzRiZGQ2OSIsInVzZXJfaWQiOjF9.bw_QXaqUVzYGHowcqtT_awDLe2XSQKb93oxeoLk_FoQ


# {
#     "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY1OTU1OTc2MiwianRpIjoiMTJkZDk4NTc0OTMzNDg1NDg0NTA5ZTVmMjI3MDcyM2EiLCJ1c2VyX2lkIjoxfQ.ndNmLTR4CpoPkr3CrnBxf8-oOrfYE41QYatATSBoVFE",
#     "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5NTU5NzYyLCJqdGkiOiJiZGMyMjU5MjdiMjE0ZGQ5YjRhNzgyNjlhOTFlNGNiZCIsInVzZXJfaWQiOjF9.n53KwfdeBPgZ0ZXaDUznoc6ZhTzcK3EoLIDPzUQKsKg"
# }

# eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5NTYwNTA5LCJqdGkiOiIzZTgwN2NlYjhmNmQ0ODc3YWI5MzRlZDcyYzRiZGQ2OSIsInVzZXJfaWQiOjF9.bw_QXaqUVzYGHowcqtT_awDLe2XSQKb93oxeoLk_FoQ
